# Generated by Django 5.1.2 on 2024-10-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Can view catalog of vehicles')]},
        ),
    ]
